from sqlalchemy import Column, Integer, String, Float
from config.db import Base

class RegGuia(Base):
    __tablename__ = "reg_guia"
    
    idreg = Column(Integer, primary_key=True)
    fecreg = Column(String)
    fecmod = Column(String)
    streg = Column(Integer)
    stsrc = Column(Integer)
    stpkg = Column(Integer)
    stbox = Column(Integer)
    idguia = Column(Integer)
    idemp = Column(Integer)
    emp_razon = Column(String)
    fecguia = Column(String)
    guia = Column(Integer)
    snombres = Column(String)
    sapeuno = Column(String)
    sapedos = Column(String)
    sapetres = Column(String)
    spais = Column(Integer)
    steluno = Column(Integer)
    steldos = Column(Integer)
    dnombres = Column(String)
    dapeuno = Column(String)
    dapedos = Column(String)
    dapetres = Column(String)
    dpais = Column(Integer)
    dteluno = Column(Integer)
    dteldos = Column(Integer)
    ddiruno = Column(String)
    ddirdos = Column(String)
    destado = Column(String)
    dciudad = Column(String)
    dzipcode = Column(Integer)
    idgrupo = Column(Integer)
    idregion = Column(Integer)
    monto = Column(Float)
    peso = Column(Float)
    productos = Column(String)
    observaciones = Column(String)